[[jBPMRemoteAPI]]
== Remote API

// Needed to set the xml:base attribute in the docbook <chapter> element. See fixChapters.xslt  
++++
<remark ID="base">RemoteAPI/</remark>
++++

The workbench contains an execution server (for executing processes and tasks),
which also allows you to invoke various process and task related operations
through a remote API.  As a result, you can setup your process engine "as a service"
and integrate this into your applications easily by doing remote requests and/or sending
the necessary triggers to the execution server whenever necessary (without the need to
embed or manage this as part of your application).
  
Both a REST and JMS based service are available (which you can use directly),
and a Java remote client allows you to invoke these operations using the existing
KieSession and TaskService interfaces (you also use for local interaction), making
remote integration as easy as if you were interacting with a local process engine.

++++
  <xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="Java-section.xml" />  
  <xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="REST-section.xml" />
  <xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="REST-Query-section.xml" />
  <xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="JMS-section.xml" />
  <xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="Additional-section.xml" />
++++
