:icons:

[[remote.additional]]
== Additional Information 

=== REST Serialization: JAXB or JSON

Except for the <<remote.rest.execute,Execute calls>>, all other REST calls described
below can use either JAXB or JSON.

All REST calls, unless otherwise specified, use JAXB serialization.

When using JSON, make sure to add the JSON media type (`"application/json"`) to the
`ACCEPT` header of your REST call.


[[remote.serialization.user.classes]]
=== Sending and receiving user class instances

Sometimes, users may wish to pass instances of their own classes as parameters to
commands sent in a REST or Webservice request or JMS message. In order to do this, there are a 
number of requirements.

* The user-defined class satisfy the following in order to be property serialized
  and deserialized:
** It should be possible to serialize and deserialize the user-defined class using JAXB.  For 
   simple custom classes, this might be available out-of-the-box, but for more complex types, this 
   might mean the classes need to be correctly annotated with JAXB annotations, including the 
   following: 
*** The user-defined class must be annotated with a `javax.xml.bind.annotation.XmlRootElement`
    annotation with a non-empty `name` value
*** All fields or getter/setter methods must be annotated with a
    `javax.xml.bind.annotation.XmlElement` or `javax.xml.bind.annotation.XmlAttribute` annotations.
** Furthermore, the following usage of JAXB annotations is recommended:
*** Annotate the user-defined class with a `javax.xml.bind.annotation.XmlAccessorType` annotation
    specifying that fields should be used, (`javax.xml.bind.annotation.XmlAccessType.FIELD`). This
    also means that you should annotate the fields (instead of the getter or setter methods)
    with `@XmlElement` or `@XmlAttribute` annotations.
*** Fields annotated with `@XmlElement` or `@XmlAttribute` annotations should also be annotated with
    `javax.xml.bind.annotation.XmlSchemaType` annotations specifying the type of the field, even
    if the fields contain primitive values.
** Use objects to store primitive values. For example, use the `java.lang.Integer` class for
    storing an integer value, and not the `int` class. This way it will always be obvious if the
    field is storing a value.
** The user-defined class definition must implement a no-arg constructor.
** Any fields in the user-defined class must either be object primitives (such as a `Long` or
   `String`) or otherwise be objects that satisfy the same requiremends in this list (correct
   usage of JAXB annotations and a no-arg constructor).
** The class definition must be included in the deployment jar (kjar) of the deployment that the 
   command (request) is sent to.
** The sender must pass the deployment id in the header of the request. This property is necessary 
   to able to load the proper classes from the deployment itself before deserializing the message 
   on the server side. 
*** For REST requests, this means that the "Kie-Deployment-Id" header property 
    must be set.  
*** For JMS messages, the `deploymentId` string property on the JMS text message must be set. 

[NOTE]
.Retrieving process variables
===============
While _submitting_ an instance of a user-defined class is possible via both the JMS and REST API,
_retrieving_ an instance of the process variable is only possible via the REST API.
===============

=== Including the deployment id

When interacting with the Remote API, users may want to pass instances of their own classes as parameters
to certain operations. As mThis will only be possible if the KJar for a deployment includes these classes.

REST calls that involve the `TaskService` (e.g. that start with `/task`..), often do not
contain any information about the associated deployment. In that case, an extra query parameter will have to be
added to the REST call so that the server can find the appropriate deployment with the class (definition) and
correctly deserialize the information passed with the call.


For these REST calls which do not contain the deployment id, you'll need to add the following parameter:

.Deployment id query parameter
[cols="m<,m<,d<", options="header"]
|===================================================================================================
| Parameter name | Description
| deploymentId   | Value (must match the regex `[a-zA-Z0-9-:\.]+`) specifies the deployment which contains 
                   the user-defined class(es) needed to correctly deserialze information passed in the call
|===================================================================================================

=== REST Pagination

Some of the REST calls below return lists of information. The results of these operations can be
_paginated_, which means that the lists can be split up and returned according to the parameters sent by the user.

For example, if the REST call parameters indicate that _page 2_ with _page size 10_ should
be returned for the results, then results 10 to (and including) 19 will be returned.

The first page is always page 1 (as opposed to page "0").

.Pagination query parameter syntax
[cols="m<,m<,d<", options="header"]
|===================================================================================================
| Parameter name | Description
| page           | The page number requested. The default value is 1.
| p              | Synonym for the above `page` parameter.
| pageSize       | The number of elements per page to return. The default value is 10.
| s              | Synonym for the above `pageSize` parameter.
|===================================================================================================

If both a "long" pagination parameter and its synonym are used, then only the value from the "long" variant is used. For
example, if the `page` is given with a value of 11 and the `p` parameter is given with a value of 37, then the value of the
`page` parameter, _11_ , will be used and the `p` parameter will be ignored.

For the following operations, pagination is _always_ used. See above for the default values used.


.REST operations using pagination
[cols="2*d<", options="header"]
|===================================================================================================
| REST call URL                                            | Short Description
| `/history/instance`                                      | Returns a list of `ProcessInstanceLog` instances
| `/history/instance/{procInstid}`                         | Returns a list of `ProcessInstanceLog` instances
| `/history/instance/{procInstId}/child`                   | Returns a list of `ProcessInstanceLog` instances
| `/history/instance/{procInstId}/node`                    | Returns a list of `NodeInstanceLog` instances
| `/history/instance/{procInstId}/node/{nodeId}`           | Returns a list of `NodeInstanceLog` instances
| `/history/instance/{procInstId}/variable`                | Returns a list of `VariableInstanceLog` instances
| `/history/instance/{procInstId}/variable/{varId}`        | Returns a list of `VariableInstanceLog` instances
| `/history/variable/{variableId}`                         | Returns a list of `VariableInstanceLog` instances
| `/history/variable/{variableId}/instances`               | Returns a list of `ProcessInstance` instances
| `/history/variable/{variableId}/value/{value}`           | Returns a list of `ProcessInstance` instances
| `/history/variable/{variableId}/value/{value}/instances` | Returns a list of `ProcessInstance` instances
| `/history/process/{procDefId}`                           | Returns a list of `ProcessInstanceLog` instances
| `/task/query`                                            | Returns a list of `TaskSummaryImpl` instances
| `/query/runtime/task`                                    | Returns a `JaxbQueryTaskResult` instance
| `/query/runtime/process`                                 | Returns a `JaxbQueryProcessInstanceResult` instance
|===================================================================================================

=== REST Map query parameters

If you're triggering an operation with a REST API call that would normally (e.g. when interacting the same operation on a
local `KieSession` or `TaskService` instance) take an instance of a `java.util.Map` as one of its parameters,
you can submit key-value pairs to the operation to simulate this behaviour by passing a query parameter whose name starts
with `map_`.

.Query parameter examples
====================================================================================================
If you pass the query parameter `map_kEy=vAlue` in a REST call, then the
`Map` that's passed to the actual underlying `KieSession` or `TaskService`
operation will contain this (`String, String`) key value pair: `"kEy" => "vAlue"`.
You could pass this parameter like so: 

[source]
----------------------------------------------------------------------------------------------------
http://localhost:8080/kie-wb/rest/runtime/myproject/process/wonka.factory.loompa.hire/start?map_kEy=vAlue
----------------------------------------------------------------------------------------------------

Map query parameters also use the object query parameter syntax described
below, so the following query parameter, `map_total=5000` will be translated
into a key-value pair in a map where the key is the String "total" and the
value is a Long with the value of 5000. For example: 

[source]
----------------------------------------------------------------------------------------------------
http://localhost:8080/kie-wb/rest/runtime/myproject/process/wonka.factory.oompa.chocolate/start?map_total=5000`
----------------------------------------------------------------------------------------------------

====================================================================================================

The following operations take query map parameters:

- `/runtime/{deploymentId}/process/{processDefId}/start`
- `/runtime/{deploymentId}/workitem/{processItemId}/complete`
- `/runtime/{deploymentId}/withvars/process/{processDefId}/start`
- `/task/{taskId}/complete`
- `/task/{taskId}/fail`

=== REST Number query parameters

While REST calls obviously only take strings as query parameters, using the following
notation for query parameters will mean that the string is translated into a different type
of object when the value of the string is used in the actual operation:

.Number query parameter syntax
[cols="m<,m<,d<", options="header"]
|=======================================
| Regex syntax   | Type
| \d+            | Long
| \d+i           | Integer
| \d+l           | Long
|=======================================

=== Runtime strategies

The remote API calls allow access to the underlying deployments, regardless of whether these 
deployments use the `Singleton`, `Per-Process-Instance` or `Per-Request` strategies.

While there's enough information in the URL in order to access deployments that use the
`Singleton` , or `Per-Request` strategies, that's not always the case with the
`Per-Process-Instance` runtimes because the remote API operation will need the process instance id 
in order to identify the deployment.

Therefore, for REST calls for which the URL does not contain the process instance id, you'll need 
to add the following parameter:

.Per-Process-Instance runtime query parameter
[cols="m<,m<,d<", options="header"]
|===================================================================================================
| Parameter name       | Description
| `runtimeProcInstId`  | Value (must match the regex `[0-9]+`) specifies the process instance id
                       that identifies the underlying `Per-Process-Instance` deployment +
                       Will have no effect if the underlying deployment uses the `Singleton`
                       or `Per-Request` strategy
|===================================================================================================


