:icons:

[[remote.java]]
== Remote Java API
  
The Remote Java API provides `KieSession`, `TaskService` and `AuditService` interfaces to the JMS and REST APIs.
    
The interface implementations provided by the Remote Java API take care of the underlying
logic needed to communicate with the JMS or REST APIs. In other words, these implementations
will allow you to interact with a remote workbench instance (i.e. KIE workbench or the jBPM
Console) via known interfaces such as the `KieSession` or `TaskService` interface, 
without having to deal with the underlying transport and serialization details.
    
The first step in interacting with the remote runtime is to use a `RemoteRuntimeEngineFactory` 
static `newRestBuilder()`, `newJmsBuilder()` or `newCommandWebServiceClientBuilder()` to create 
a builder instance. Use the new builder instance to configure and to create a `RuntimeEngine`
instance to interact with the server. 

Each of the REST, JMS or WebService `RemoteClientBuilder` instances exposes different 
methods that allow the configuration of properties like the base URL of the REST API, JMS queue 
locations or timeout while waiting for responses.

[IMPORTANT]
.The Remote Java API provides clients, not "instances"
======
While the `KieSession`, `TaskSerivce` and `AuditService` instances provided by the Remote Java API 
may "look" and "feel" like local instances of the same interfaces, please make sure to remember 
that these instances are only wrappers around a REST or jMS client that interacts with a remote REST or JMS
API. + 

{nbsp} +

This means that if a requested operation fails on the _server_, the Remote Java API client instance 
on the _client_ side will throw a `RuntimeException` indicating that the REST call failed. This is 
different from the behaviour of a "real" (or local) instance of a `KieSession`, `TaskSerivce` and 
`AuditService` instance because the exception the local instances will throw will relate to how the 
operation failed. Operations on a Remote Java API client instance that would normally throw other 
exceptions (such as the `TaskService.claim(taskId, userId)` operation when called by a user who is 
not a potential owner), will now throw a `RuntimeException` instead when the requested operation 
fails on the server. +

{nbsp} +

Also, while local instances require different handling (such as having to dispose of a `KieSession`),
client instances provided by the Remote Java API hold no state and thus do not require any special 
handling. + 

{nbsp} +

Finally, the instances returned by the client `KieSession` and `TaskService` instances (for example, 
process instances or task summaries) are not the same (internal) objects as used by the core engines. 
Instead, these returned instances are simple data transfer objects (DTOs) that implement the same 
interfaces but are designed to only return the associated data. Modifying or casting these returned 
instances to an internal implementation class will not succeed.
======
   
.Creating a Remote Java Client Instance
****************************************************************************************************
The following is a simple example of creating a REST-based client. The `appName` variable in the
code below will be either "business-central" or "kie-wb" dependending on whether you're using product 
or community. 

[source,java,linenums,indent=0]
-------------
include::{codeDir}/org/kie/remote/client/documentation/rest/RestJavaApiExamples.java[tags=simpleBuilderExample]
-------------
<1> Create the appropriate builder instance. The method `.newJmsBuilder()` is available to create JMS 
based builder instances
<2> Call the appropriate methods and pass the appropriate parameters to configure the client
<3> "Build" or instantiate the actual client `RuntimeEngine` instance which you can then use to 
interact with the server
****************************************************************************************************

=== Remote REST Java API Client Configuration

Each builder has a number of different (required or optional) methods to configure a client 
`RuntimeEngine` instance. 

- Methods with *^always^* next to them are *always* required.
- Methods with ^when^ next to them are _required depending on the factors described_ 
("required _when_...") and otherwise optional.
- All other methods are optional. 

.Remote Rest Runtime Engine Builder methods

*`addDeploymentId(String deploymentId)`*^when^:: Set the deployment id of the deployment
+
_Required when_:;; doing an operation on a client instance that affects a process instance
*`addExtraJaxbClasses(Class... extraJaxbClasses )`*^when^:: Add extra classes to the classpath available 
to the serialization mechanisms
+
When passing instances of user-defined classes in a Remote Java API call, it's important to 
use this method first to add the classes so that the class instances can be serialized correctly.
+
_Required when_:;; passing custom class instances as arguments to an operation on a client instance
*`addPassword(String password)`^always^*:: Set the password of the user connecting to the server
*`addProcessInstanceId(long process)`*^when^:: Set the process instance id of the deployment
+
_Required when_:;; interacting with a `PER_PROCESS_INSTANCE` deployment
*`addTimeout(int timeoutInSeconds)`*:: Set the timeout for the REST call
+
The default is 5 seconds. 
*`addUrl(URL serverInstanceUrl)`^always^*:: Set the URL for the application instance 
+ 
This should be a URL that roughly corresponds to `http://server:port/business-central/` 
or `http://server:port/kie-wb/`. 
*`addUserName(String userName)`^always^*:: Set the name of the user connecting to the server
*`clearJaxbClasses()`*:: Clears the list of (user-defined) Classes that the client instance should
know about

==== Example REST Remote Java Client Configuration

The following example illustrates how the Remote Java API can be used with the REST API.

[source,java,linenums,indent=0]
-------------
include::{codeDir}/org/kie/remote/client/documentation/rest/RestJavaApiExamples.java[tags=simpleRestBuilderExample]
-------------

[[remote.java.api.jms]]         
=== Remote JMS Java API Client Configuration

When configuring the remote JMS client, you must choose one of the following ways to configure
the JMS connection:

. Pass the `ConnectionFactory` instance and the _KieSession_, _TaskService_ and _Response_ `Queue`
  instances when configuring the remote java client. To do that, please use the following methods:
  - `addConnectionFactory(ConnectionFactory)`
  - `addKieSessionQueue(Queue)`
  - `addTaskServiceQueue(Queue)`
  - `addResponseQueue(Queue)`
  - `addHostName(String)`
  - `addJmsConnectorPort(String)`
. _or_ pass a remote `InitialContext` instance that contains references to the necessary
  `ConnectionFactory` and `Queue` instances (see previous bullet). 
  - please then use the method `addRemoteInitialContext(InitialContext)`
. _or_ pass a String with the hostname of the JBoss EAP server that KIE Workbench is running on
  - please then use the method `addJbossServerHostName(String)`

In addition, if you are doing an operation on a task via the remote JMS client (and are not
using the `disableTaskSecurity()` method), then you must also configure SSL. The following methods
(described in more detail below) are available for this: 

- `addHostName(String)`
- `addJmsConnectorPort(int)`
- `addKeystoreLocation(String)`
- `addKeystorePassword(String)`
- `addTruststoreLocation(String)`
- `addTruststorePassword(String)`
- `useKeystoreAsTruststore()`

==== Example JMS Remote Java Client Configuration 

.Example JMS Remote Java Client Configuration with a remote `javax.jms` classes 
****************************************************************************************************
The following example illustrates how to configure a Remote Java API JMS client using
instances of the `ConnectionFactory` and `Queue` classes.

[source,java,linenums,indent=0]
-------------
include::{codeDir}/org/kie/remote/client/documentation/jms/JmsJavaApiExamples.java[tags=connFactoryJmsBuilderExample]
-------------
<1> The names of the `ConnectionFactory` and `Queue` instances may differ depending on your application server
<2> Here we add the connection factory and queue instances.
<3> If we are not using SSL, but are doing operations on tasks, then we have to explictly call 
the `disableTaskSecurity()` method. SSL is necessary for security reasons (plain-text password in 
message) when doing task operations via the remote Java API. 
****************************************************************************************************

.Example JMS Remote Java Client Configuration with a remote `InitialContext` instance 
****************************************************************************************************
The following example illustrates how to configure a Remote Java API JMS client using
a remote `InitialContext` instance. See your application server documentation for how to instantiate
a remote instance of your application server's `InitialContext`.

[source,java,linenums,indent=0]
-------------
include::{codeDir}/org/kie/remote/client/documentation/jms/JmsJavaApiExamples.java[tags=initContextJmsBuilderExample]
-------------
****************************************************************************************************

.Example JMS Remote Java Client Configuration with JBoss EAP hostname 
****************************************************************************************************
The following example illustrates how to configure a Remote Java API JMS client using
the hostname of the JBoss EAP server on which kie-wb or business-central is running.

[source,java,linenums,indent=0]
-------------
include::{codeDir}/org/kie/remote/client/documentation/jms/JmsJavaApiExamples.java[tags=jbossHostNameJmsBuilderExample]
-------------
****************************************************************************************************

==== Remote JMS Runtime Engine Builder methods

Each builder has a number of different (required or optional) methods to configure a client 
`RuntimeEngine` instance. 

- Methods with *^always^* next to them are *always* required.
- Methods with ^when^ next to them are _required depending on the factors described_ 
("required _when_...") and otherwise optional.
- All other methods are optional. 

.Remote JMS Runtime Engine Builder methods

*`addConnectionFactory(ConnectionFactory connectionFactory)`*^when^:: Add a `ConnectionFactory`
used to create JMS session to send and receive messages
+
_Required when_:;; configuring the JMS java client by passing `ConnectionFactory` and `Queue`
instances
*`addDeploymentId(String deploymentId)`*^when^:: Set the deployment id of the deployment
+
_Required when_:;; doing an operation on a client instance that affects a process instance -- this 
also includes completing or failing tasks created by process instances
*`addExtraJaxbClasses(Class... extraJaxbClasses )`*^when^:: Add extra classes to the client
for when user-defined class instances are passed as parameters to client methods
+
When passing instances of user-defined classes in a Remote Java API call, it's important to 
use this method first to add the classes so that the class instances can be serialized correctly.
+
_Required when_:;; passing custom class instances as arguments to an operation on a client instance
*`addHostName(String hostname)`*^when^:: Set the host name for the server that the client is making a
JMS connection with
+
_Required when_:;; configuring the JMS java client by setting `ConnectionFactory` and `Queue`
instances
+ 
configuring the JMS java client to use SSL
*`addJbossServerHostName(String hostname)`*:: Set the host name of the JBoss EAP server that the 
client is making a JMS connection with
+
After using this method, no other configuration is needed with regards to the server. However, 
additional server parameters (host name, port) may be needed when also configuring SSL.
+
Make sure that the EAP version-appropriate `org.jboss.naming:jboss-naming` dependency is available 
on the classpath when doing this
*`addJmsConnectorPort(int port)`*^when^:: Set the port used for the JMS connection connection with
the server
+
_Required when_:;; configuring the JMS java client by passing `ConnectionFactory` and `Queue`
instances
+ 
configuring the JMS java client to use SSL
*`addKeystoreLocation(String keystorePath)`*^when^:: Set the location (path) of the keystore
_Required when_:;; configuring the JMS java client to use SSL
*`addKeystorePassword(String keystorePassword)`*^when^:: Set the password for the keystore
_Required when_:;; configuring the JMS java client to use SSL
*`addKieSessionQueue(Queue ksessionQueue)`*^when^:: Pass the `javax.jms.Queue` instance representing
the _KIE.SESSION_ queue used to receive process instance requests from the client
_Required when_:;; configuring the JMS java client by setting `ConnectionFactory` and `Queue`
instances
*`addPassword(String password)`^always^*:: Set the password of the user connecting to the server
*`addProcessInstanceId(long process)`*^when^:: Set the process instance id of the deployment
+
_Required when_:;; interacting with a _`PER_PROCESS_INSTANCE`_ deployment
*`addRemoteInitialContext(InitialContext remoteInitialContext)`*:: Set the remote `InitialContext` 
instance from the remote application server, which is then used to retrieve the `ConnectionFactory`
and `Queue` instances
+
After using this method, no other configuration is needed with regards to the server. However, 
additional server parameters (host name, port) may be needed when also configuring SSL.
*`addResponseQueue(Queue responseQueue)`*^when^:: Pass the `javax.jms.Queue` instance representing
the _KIE.RESPONSE_ queue used to send responses to the client
_Required when_:;; configuring the JMS java client by setting `ConnectionFactory` and `Queue`
instances
*`addTaskServiceQueue(Queue taskServiceQueue)`*^when^:: Pass the `javax.jms.Queue` instance representing
the _KIE.TASK_ queue used to receive task operation requests to the client
_Required when_:;; configuring the JMS java client by setting `ConnectionFactory` and `Queue`
instances
*`addTimeout(int timeoutInSeconds)`*:: Set the timeout for the JMS message. The default is 5 seconds. 
*`addTruststoreLocation(String truststorePath)`*^when^:: Set the location (path) of the keystore
_Required when_:;; configuring the JMS java client to use SSL
*`addTruststoreLocation(String truststorePassword)`*^when^:: Set the password for the keystore
_Required when_:;; configuring the JMS java client to use SSL
*`addUserName(String userName)`^always^*:: Set the name of the user connecting to the server
+
This is also the user whose permissions will be used when doing any task operations
*`clearJaxbClasses()`*:: Clears the list of (user-defined) Classes that the client instance should
know about
*`disableTaskSecurity()`*:: Enables configuration of a client that can send task-related operation
requests without having to use SSL. If this option is *not* used and a task operation is called, the
client will throw an exception.
*`useKeystoreAsTruststore()`*:: Uses the same file (location) and password for the truststore
configuration when configuring SSL.


[IMPORTANT]
====================================================================================================
In order to instantiate a remote `InitialContext` via JNDI, the application-server-specific 
dependencies need to be included on the classpath.  

For JBoss EAP 6, the artifact (jar) containing this class is the
`org.jboss:jboss-remote-naming` artifact (jar), version
`1.0.5.Final` or higher. Depending on the version of AS 7 or EAP 6 that you
use, this version may vary.

If you are using a _different_ application server, please see your specific
application server documentation for the parameters and artifacts necessary to create an
`InitialContextFactory` instance or otherwise get a remote
`InitialContext` instance (via JNDI) from the application server instance.
====================================================================================================

==== Example JMS client configuration and usage with SSL


The following example illustrates how to configure a Remote Java API JMS client using
a remote `InitialContext` instance along with SSL. In this case, the same file is being used as
both the client's keystore (the client's identifying keys and certificates) and as the client's 
truststore (the client's list of trusted certificates from other parties, in this case, the server). 

[source,java,linenums,indent=0]
-------------
include::{codeDir}/org/kie/remote/client/documentation/jms/JmsJavaApiExamples.java[tags=sslJmsBuilderExample]
-------------
      
[[remote.java.api.ws.command]]         
=== Remote CommandWebService Java API Client Configuration

Starting with this release, a simple webservice has been added to the remote API. 

.Example WebService Remote Java Client Configuration 
****************************************************************************************************
The following example illustrates how to configure a Remote Java API WebService client using
the hostname of the JBoss EAP server on which kie-wb or business-central is running.

[source,java,linenums,indent=0]
-------------
include::{codeDir}/org/kie/remote/client/documentation/ws/WebserviceJavaApiExamples.java[tags=simpleWebserviceBuilderExample]
-------------
<1> All commands that can be used with the webservice can be found in the `org.kie.remote.jaxb.gen` 
package in the `kie-remote-client` module. These commands contain the same data as the commands
that they are based on (that have the same name) in the core jbpm and drools modules.
<2> The `addExtraJaxbClasses(Class...)` method must be used when using instances of user-defined
classes in a command sent in a webservice request.
<3> Similar to the REST `/execute` method, multiple commands can be sent in one webservice request
****************************************************************************************************

.Remote Webservice Client Builder methods

*`addDeploymentId(String deploymentId)`*^when^:: Set the deployment id of the deployment
+
_Required when_:;; doing an operation on a client instance that affects a process instance -- this 
also includes completing or failing tasks created by process instances
*`addExtraJaxbClasses(Class... extraJaxbClasses )`*^when^:: Add extra classes to the client
for when user-defined class instances are passed as parameters to client methods
+
When passing instances of user-defined classes in a Remote Java API call, it's important to 
use this method first to add the classes so that the class instances can be serialized correctly.
+
_Required when_:;; passing custom class instances as arguments to an operation on a client instance
*`addServerUrl(URL applicationUrl)`^always^*:: Set the URL for the application (kie-wb or 
business-central) that the webservice request will be sent to
*`addPassword(String password)`^always^*:: Set the password of the user connecting to the server
*`addTimeout(int timeoutInSeconds)`*:: Set the timeout for the Webservice response. The default is 5 seconds. 
*`addUserName(String userName)`^always^*:: Set the name of the user connecting to the server
+
This is also the user whose permissions will be used when doing any task operations
*`setWsdlLocationRelativePath()`*:: OCRAM
*`useHttpRedirect()`*:: OCRAM

////
=== Remote REST Java API exceptions
      
Because the Remote REST Java API clients implement the existing `KieSession`,
`TaskService` and `AuditService` interfaces, the exceptions thrown by the 
client implementations must be instances of a `RuntimeException`.
      
The table below lists the exceptions thrown by the different client interfaces.

.Exceptions thrown by the Remote REST Java API client implementations
[cols="3*d<",options="header"]
[cols="d<,d<,d<",options="header"]
|===================================================================================================
| Name             | Type             | Description 
| fill me   | yup | this is a description
|===================================================================================================
////

=== Supported methods
    
As mentioned above, the Remote Java API provides client-like instances of the `RuntimeEngine`, `KieSession`,
      `TaskService` and `AuditService` interfaces.
    
This means that while many of the methods in those interfaces are available, some are not. The following tables lists the methods
      which are available. Methods not listed in the below, will throw an `UnsupportedOperationException` explaining that the 
      called method is not available.
    
.Available process-related `KieSession` methods
[cols="d<,d<,d<",options="header"]
|===================================================================================================
| Return type | Method signature | Description
| `void`                   | `abortProcessInstance(` `long processInstanceId)` | Abort the process instance
| `ProcessInstance`        | `getProcessInstance(` `long processInstanceId)`   | Return the process instance
| `ProcessInstance`        | `getProcessInstance(` `long processInstanceId,` 
                             `boolean readOnly)`                            | Return the process instance
| `List<ProcessInstance>`  | `getProcessInstances()`                        | Return all (active) process instances
| `void`                   | `signalEvent(` `String signal,` `Object event)`     | Signal all (active) process instances
| `void`                   | `signalEvent(` `String signal,` `Object event,` 
                             `long processInstanceId)`                      | Signal the process instance
| `ProcessInstance`        | `startProcess(` `String processId,`
                             `CorrelationKey correlationKey,` 
                             `Map<String, Object> parameters)`              | Start a new process and return the process instance (if the process instance has not immediately completed)
| `ProcessInstance`        | `startProcess(String processId,`
                             `Map<String, Object> parameters)`              | Start a new process and return the process instance (if the process instance has not immediately completed)
|===================================================================================================
    
.Available rules-related `KieSession` methods<
[cols="d<,d<,d<",options="header"]
|===================================================================================================
| Return type | Method signature             | Description
| `Long`    | `getFactCount()`               | Return the total fact count
| `Object`  | `getGlobal(String identifier)` | Return a global fact
| `Integer` | `getId()`                      | Return the id of the `KieSession`
| `void`    | `setGlobal(String identifier,`
              `Object value)`                | Set a global fact
| `void`    | `fireAllRules()`               | Fire all rules
|===================================================================================================

.Available `WorkItemManager` methods
[cols="#*d<",options="header"]
|===================================================================================================
| Return type | Method signature | Description
| `void`      | `abortWorkItem(long workItemId)`    | Abort the work item
| `void`      | `completeWorkItem(long workItemId,`
                `Map<String, Object> results)`      | Complete the work item
| `WorkItem`  | `getWorkItem(long workItemId)`      | Return the work item
|===================================================================================================

.Available task operation `TaskService` methods
[cols="3*d<",options="header"]
|===================================================================================================
| Return type | Method signature | Description
| `Long`            | `addTask(Task task,` 
                       `Map<String, Object> params)`           | Add a new task
| `void`            | `activate(long taskId, String userId)`   | Activate a task
| `void`            | `claim(long taskId, String userId)`      | Claim a task
| `void`            | `claim(long taskId, String userId,` 
                      `List<String> groupIds)`                 | Claim a task
| `void`            | `claimNextAvailable(String userId,` 
                      `String language)`                       | Claim the next available task for a user
| `void`            | `claimNextAvailable(String userId,` 
                      `List<String> groupIds,` 
                      `String language)`                       | Claim the next available task for a user
| `void`            | `complete(long taskId, String userId,` 
                      `Map<String, Object> data)`              | Complete a task
| `void`            | `delegate(long taskId, String userId,` 
                      `String targetUserId)`                   | Delegate a task
| `void`            | `exit(long taskId, String userId)`       | Exit a task
| `void`            | `fail(long taskId, String userId,` 
                      `Map<String, Object> faultData)`         | Fail a task
| `void`            | `forward(long taskId, String userId,` 
                      `String targetEntityId)`                 | Forward a task
| `void`            | `nominate(long taskId, String userId,` 
                      `List<OrganizationalEntity>` `potentialOwners)`            | Nominate a task
| `void`            | `release(long taskId, String userId)`    | Release a task
| `void`            | `remove(long taskId, String userId)`     | Remove a task
| `void`            | `resume(long taskId, String userId)`     | Resume a task
| `void`            | `skip(long taskId, String userId)`       | Skip a task
| `void`            | `start(long taskId, String userId)`      | Start a task
| `void`            | `stop(long taskId, String userId)`       | Stop a task
| `void`            | `suspend(long taskId, String userId)`    | Suspend a task
|===================================================================================================

.Available task retrieval and query `TaskService` methods
[cols="3*d<",options="header"]
|===================================================================================================
| Return type          | Method signature 
| `Task`               | `getTaskByWorkItemId(long workItemId)`
| `Task`               | `getTaskById(long taskId)`
| `List<TaskSummary>`  | `getTasksAssignedAsBusinessAdministrator(String userId, String language)`
| `List<TaskSummary>`  | `getTasksAssignedAsPotentialOwner(String userId, String language)`
| `List<TaskSummary>`  | `getTasksAssignedAsPotentialOwnerByStatus(String userId,` `List<Status> status, String language)`
| `List<TaskSummary>`  | `getTasksOwned(String userId, String language)`
| `List<TaskSummary>`  | `getTasksOwnedByStatus(String userId, List<Status> status,` `String language)`
| `List<TaskSummary>`  | `getTasksByStatusByProcessInstanceId(long processInstanceId,` `List<Status> status, String language)`
| `List<TaskSummary>`  | `getTasksByProcessInstanceId(long processInstanceId)`
| `List<TaskSummary>   | `getTasksByVariousFields(List<Long> workItemIds,` `List<Long> taskIds,` 
                         `List<Long> procInstIds,` `List<String> busAdmins,` `List<String> potOwners,` 
                         `List<String> taskOwners,` `List<Status> status,` `boolean union)`
| `List<TaskSummary>`  | `getTasksByVariousFields(Map <String, List<?>> parameters, boolean union)`
| `Content`            | `getContentById(long contentId)`
| `Attachment`         | `getAttachmentById(long attachId)`
|===================================================================================================
    
.Available `AuditService` methods
[cols="3*d<",options="header"]
|===================================================================================================
| Return type            | Method signature 
| `List<ProcessInstanceLog>`   | `findProcessInstances()`
| `List<ProcessInstanceLog>`   | `findProcessInstances(String processId)`
| `List<ProcessInstanceLog>`   | `findActiveProcessInstances(String processId)`
| `ProcessInstanceLog`         | `findProcessInstance(long processInstanceId)`
| `List<ProcessInstanceLog>`   | `findSubProcessInstances(long processInstanceId)`
| `List<NodeInstanceLog>`      | `findNodeInstances(long processInstanceId)`
| `List<NodeInstanceLog>`      | `findNodeInstances(long processInstanceId,` `String nodeId)`
| `List<VariableInstanceLog>`  | `findVariableInstances(long processInstanceId)`
| `List<VariableInstanceLog>`  | `findVariableInstances(long processInstanceId,` `String variableId)`
| `List<VariableInstanceLog>`  | `findVariableInstancesByName(String variableId,` `boolean onlyActiveProcesses)`
| `List<VariableInstanceLog>`  | `findVariableInstancesByNameAndValue(String variableId,` `String value,` `boolean onlyActiveProcesses)`
| `void`                       | `clear()`
|===================================================================================================
