:icons:

[[remote.rest]]
== REST

REST API calls to the execution server allow you to remotely manage processes and tasks and retrieve 
various dynamic information from the execution server. The majority of the calls are synchronous, 
which means that the call will only finish once the requested operation has completed on the server. 
The exceptions to this are the deployment `POST` calls, which will return the status of the request 
while the actual operation requested will asynchronously execute.

When using Java code to interface with the REST API, the classes used in POST operations or 
otherwise returned by various operations can be found in the `(org.kie.remote:)kie-services-client` 
JAR.

[[remote.rest.runtime]]
=== Runtime calls

This section lists REST calls that interface process instances. 

The _deploymentId_ component of the REST calls below must conform to
the following regular expression:

-----
[\w\.-]+(:[\w\.-]+){2,2}(:[\w\.-]*){0,2}
-----

For more information about the composition of the deployment id, see the 
<<remote.rest.deployment,Deployment Calls>> section.

==== Process calls

[POST] *`/runtime/_{deploymentId}_/process/_{processDefId}_/start`*

- Starts a process.
- Returns a `JaxbProcessInstanceResponse` instance, that contains basic information about the 
  process instance.
- Notes: 
* The _processDefId_ component of the URL must conform to the following regex: `[_a-zA-Z0-9-:\.]+`
- Parameters: 
* This operation takes _map query parameters_ (see below), which will be used as parameters for the 
  process instance.
* You can only pass basic types (as map query parameters) using this URL. If you want to pass 
  complex and/or custom classes, you should use the Java Remote API instead.

[POST] *`rest/runtime/_{deploymentId}_/process/_{processDefId}_/startform`*

- Checks that exists the process idetified by _processDefId_ on the given deployment and generates 
  an URL to show the start form on a remote application.
- Returns a `JaxbProcessInstanceFormResponse` instance, that contains the URL to the start process 
  form.
- Notes:
* The _processDefId_ component of the URL must conform to the following regex: `[_a-zA-Z0-9-:\.]+`

[GET] *`/runtime/_{deploymentId}_/process/instance/_{procInstId}_`*

- Does a (read only) retrieval of the process instance. This operation will fail (code 400) if the 
  process instance has been completed.
- Returns a `JaxbProcessInstanceResponse` instance.
- Notes: 
* The _procInstId_ component of the URL must conform to the following regex: `[0-9]+`

[POST] *`/runtime/_{deploymentId}_/process/instance/_{procInstId+}_/abort`*

- Aborts the process instance.
- Returns a `JaxbGenericResponse` indicating whether or not the operation has succeeded.
- Notes: 
* The _procInstId_ component of the URL must conform to the following regex: `[0-9]+`

[POST] *`/runtime/_{deploymentId}_/process/instance/_{procInstId}_/signal`*

- Signals the process instance.
- Returns a `JaxbGenericResponse` indicating whether or not the operation has succeeded.
- Notes: 
* The _procInstId_ component of the URL must conform to the following regex: `[0-9]+`
- Parameters: This operation takes a `signal` and a `event` query parameter.
* The `signal` parameter value is used as the name of the signal. This parameter is required.
* The `event` parameter value is used as the value of the event. This value may use the _number 
  query parameter_ syntax described above.

[GET] *`/runtime/_{deploymentId}_/process/instance/_{procInstId}_/variables`*

- Gets the list of process variables in a process instance.
- Returns a `JaxbVariablesResponse`
- Notes: 
* The _procInstId_ component of the URL must conform to the following regex: `[0-9]+`

[POST] *`/runtime/_{deploymentId}_/signal`*

- Signals the `KieSession`
- Returns a `JaxbGenericResponse` indicating whether or not the operation has succeeded.
- Notes: 
* The _procInstId_ component of the URL must conform to the following regex: `[0-9]+`
- Parameters: This operation takes a `signal` and a `event` query parameter.
*  The `signal` parameter value is used as the name of the signal. This parameter is required.
* The `event` parameter value is used as the value of the event. This value may use the _number query parameter_ syntax described above.

[GET] *`/runtime/_{deploymentId}_/workitem/_{workItemId}_`*

- Gets a `WorkItem` instance
- Returns a `JaxbWorkItem` instance
- Notes: 
* The _workItemId_ component of the URL must conform to the following regex: `[0-9]+`

[POST] *`/runtime/_{deploymentId}_/workitem/_{workItemId}_/complete`*

- Completes a `WorkItem`
- Returns a `JaxbGenericResponse` indicating whether or not the operation has succeeded
- Notes: 
* The _workItemId_ component of the URL must conform to the following regex: `[0-9]+`
- Parameters: 
* This operation takes _map query parameters_, which are used as input to signify the results for completion of the work item.
* You can only pass basic types (as map query parameters) using this URL. If you want to pass complex and/or custom classes, 
  you should use the Java Remote API instead.

[POST] *`/runtime/_{deploymentId}_/workitem/{workItemId: [0-9-]+}/abort`*

- Aborts a `WorkItem`
- Returns a `JaxbGenericResponse` indicating whether or not the operation has succeeded
- Notes: 
* The _workItemId_ component of the URL must conform to the following regex: `[0-9]+`


==== Process calls "with variables"

[POST] *`/runtime/_{deploymentId}_/withvars/process/_{processDefId}_/start`*

- Starts a process and retrieves the list of variables associated with the process instance
- Returns a `JaxbProcessInstanceWithVariablesResponse` that contains:
* Information about the process instance (with the same fields and behaviour as the `JaxbProcessInstanceResponse`
* A key-value list of the variables available in the process instance.
- Notes: 
* The _processDefId_ component of the URL must conform to the following regex: `[_a-zA-Z0-9-:\.]+`

[POST] *`/runtime/_{deploymentId}_/withvars/process/instance/_{procInstId}_`*

- Starts a process and retrieves the list of variables associated with the process instance
- Returns a `JaxbProcessInstanceWithVariablesResponse` (see the above REST call)
- Notes: 
* The _processInstId_ component of the URL must conform to the following regex: `[0-9]+`

[POST] *`/runtime/_{deploymentId}_/withvars/process/instance/_{procInstId}_/signal`*

- Signals a process instance and retrieves the list of variables associated it
- Returns a `JaxbProcessInstanceWithVariablesResponse` (see above)
- Notes: 
* The _processInstId_ component of the URL must conform to the following regex: `[0-9]+`
- Parameters:: This operation takes a `signal` and a `event` query parameter.
* The `signal` parameter value is used as the name of the signal. This parameter is required.
* The `event` parameter value is used as the value of the event. This value may use the _number query parameter_ syntax described above.

==== History calls

[POST] *`/history/clear`*

- Cleans (deletes) all history logs

[GET] *`/history/instances`*

- Gets a list of `ProcessInstanceLog` instances
- Returns a `JaxbHistoryLogList` instance that contains a list of `JaxbProcessInstanceLog` instances
- Notes: 
* This operation responds to pagination parameters

[GET] *`/history/instance/_{procInstId}_`*

- Gets the `ProcessInstanceLog` instance associated with the specified process instance
- Returns a `JaxbHistoryLogList` instance that contains a `JaxbProcessInstanceLog` instance
- Notes: 
* The _processInstId_ component of the URL must conform to the following regex: `[0-9]+`
- Parameters: This operation responds to pagination parameters

[GET] *`/history/instance/_{procInstId}_/child`*

- Gets a list of `ProcessInstanceLog` instances associated with any child/sub-processes associated with the specified process instance
- Returns a `JaxbHistoryLogList` instance that contains a list of `JaxbProcessInstanceLog` instances
- Notes: 
* The _processInstId_ component of the URL must conform to the following regex: `[0-9]+`
- Parameters: This operation responds to pagination parameters

[GET] *`/history/instance/_{procInstId}_/node`*

- Gets a list of `NodeInstanceLog` instances associated with the specified process instance
- Returns a `JaxbHistoryLogList` instance that contains a list of `JaxbNodeInstanceLog` instances
- Notes: 
* The _processInstId_ component of the URL must conform to the following regex: `[0-9]+`
- Parameters: This operation responds to pagination parameters

[GET] *`/history/instance/_{procInstId}_/variable`*

- Gets a list of `VariableInstanceLog` instances associated with the specified process instance
- Returns a `JaxbHistoryLogList` instance that contains a list of `JaxbVariableInstanceLog` instances
- Notes: 
* The _processInstId_ component of the URL must conform to the following regex: `[0-9]+`
- Parameters: This operation responds to pagination parameters

[GET] *`/history/instance/_{procInstId}_/node/_{nodeId}_`*

- Gets a list of `NodeInstanceLog` instances associated with the specified process instance that have the given (node) id
- Returns a `JaxbHistoryLogList` instance that contains a list of `JaxbNodeInstanceLog` instances
- Notes: 
* The _processInstId_ component of the URL must conform to the following regex: `[0-9]+`
* The _nodeId_ component of the URL must conform to the following regex: `[a-zA-Z0-9-:\.]+`
- Parameters: This operation responds to pagination parameters

[GET] *`/history/instance/_{procInstId}_/variable/_{varId}_`*

- Gets a list of `VariableInstanceLog` instances associated with the specified process instance that have the given (variable) id
- Returns a `JaxbHistoryLogList` instance that contains a list of `JaxbVariableInstanceLog` instances
- Notes: 
* The _processInstId_ component of the URL must conform to the following regex: `[0-9]+`
* The _varId_ component of the URL must conform to the following regex: `[a-zA-Z0-9-:\.]+`
- Parameters: This operation responds to pagination parameters

[GET] *`/history/process/_{processDefId}_`*

- Gets a list of `ProcessInstanceLog` instances associated with the specified process definition
- Returns a `JaxbHistoryLogList` instance that contains a list of `JaxbProcessInstanceLog` instances
- Notes: 
* The _processDefId_ component of the URL must conform to the following regex: `[_a-zA-Z0-9-:\.]+`
- Parameters:  This operation responds to pagination parameters

==== History calls that search by variable

[GET] *`/history/variable/_{varId}_`*

- Gets a list of `VariableInstanceLog` instances associated with the specified variable id
- Returns a `JaxbHistoryLogList` instance that contains a list of `JaxbVariableInstanceLog` instances
- Notes: 
* The _varId_ component of the URL must conform to the following regex: `[a-zA-Z0-9-:\.]+`
- Parameters: This operation responds to pagination parameters

[GET] *`/history/variable/_{varId}_/value/_{value}_`*

- Gets a list of `VariableInstanceLog` instances associated with the specified variable id that contain the value specified
- Returns a `JaxbHistoryLogList` instance that contains a list of `JaxbVariableInstanceLog` instances
- Notes: 
* Both the _varId_ and _value_ components of the URL must conform to the following regex: `[a-zA-Z0-9-:\.]+`
- Parameters:: This operation responds to pagination parameters

[GET] *`/history/variable/{varId}/instances`*

- Gets a list of `ProcessInstance` instances that contain the variable specified by the given variable id.
- Returns a `JaxbProcessInstanceListResponse` instance that contains a list of `JaxbProcessInstanceResponse` instances
- Notes: 
* The _varId_ component of the URL must conform to the following regex: `[a-zA-Z0-9-:\.]+`
- Parameters: This operation responds to pagination parameters

[GET] *`/history/variable/{varId}/value/{value}/instances`*

- Gets a list of `ProcessInstance` instances that contain the variable specified by the given variable id which contains the (variable) value specified
- Returns a `JaxbProcessInstanceListResponse` instance that contains a list of `JaxbProcessInstanceResponse` instances
- Notes: 
* Both the _varId_ and _value_ components of the URL must conform to the following regex: `[a-zA-Z0-9-:\.]+`
- Parameters: This operation responds to pagination parameters

==== History calls that search by variable

[GET] *`/runtime/_{deploymentId}_/history/variable/_{varId}_`*

- Gets a list of `VariableInstanceLog` instances associated with the specified variable id
- Returns a `JaxbHistoryLogList` instance that contains a list of `JaxbVariableInstanceLog` instances
- Notes: 
* The _varId_ component of the URL must conform to the following regex: `[a-zA-Z0-9-:\.]+`
- Parameters:: This operation responds to pagination parameters

[GET] *`/runtime/_{deploymentId}_/history/variable/_{varId}_/value/_{value}_`*

- Gets a list of `VariableInstanceLog` instances associated with the specified variable id that contain the value specified
- Returns a `JaxbHistoryLogList` instance that contains a list of `JaxbVariableInstanceLog` instances
- Notes: 
* Both the _varId_ and _value_ components of the URL must conform to the following regex: `[a-zA-Z0-9-:\.]+`
- Parameters: This operation responds to pagination parameters

[GET] *`/runtime/_{deploymentId}_/history/variable/{varId}/instances`*

- Gets a list of `ProcessInstance` instances that contain the variable specified by the given variable id.
- Returns a `JaxbProcessInstanceListResponse` instance that contains a list of `JaxbProcessInstanceResponse` instances
- Notes: 
* The _varId_ component of the URL must conform to the following regex: `[a-zA-Z0-9-:\.]+`
- Parameters: This operation responds to pagination parameters

[GET] *`/runtime/_{deploymentId}_/history/variable/{varId}/value/{value}/instances`*

- Gets a list of `ProcessInstance` instances that contain the variable specified by the given variable id which contains the (variable) value specified
- Returns a `JaxbProcessInstanceListResponse` instance that contains a list of `JaxbProcessInstanceResponse` instances
- Notes: 
* Both the _varId_ and _value_ components of the URL must conform to the following regex: `[a-zA-Z0-9-:\.]+`
- Parameters:: This operation responds to pagination parameters

[[remote.rest.task]]
=== Task calls


The following section describes the three different types of task calls:
* Task REST operations that mirror the `TaskService` interface, allowing the user to interact with the remote `TaskService` instance
* The Task query REST operation, that allows users to query for `Task` instances
* Other Task REST operations that retrieve information


.Task operation authorizations
Task REST operations use the user information (used to authorize and authenticate the HTTP call) to check whether or
not the requested operations can happen. This also applies to REST calls that retrieve information, such as the task query
operation. REST calls that request information will only return information about tasks that the user is allowed to see.

With regards to retrieving information, only users associated with a task may retrieve information about the task. However,
the authorizations of progress and other modifications of task information are more complex. See the
<<jBPMTaskPermissions,Task Permissions>> section in the <<jBPMTaskService,Task Service>>
documentation for more infomration.

[NOTE]
===================
Given that many users have expressed the wish for a "super-task-user" that can execute task REST operations on all tasks,
regardless of the users associated with the task, there are now plans to implement that feature. However,
so far for the 6.x releases, this feature is not available.
===================

==== Task operation calls

All of the task operation calls described in this section use the user (id) used in the REST basic authorization as
input for the user parameter in the specific call.

Some of the operations take an optional `lanaguage` query parameter. If this parameter is not given
as a element of the URL itself, the default value of "`en-UK`" is used.

The _taskId_ component of the REST calls below must conform to the following regex:

------
[0-9]+
------


[POST] *`/task/_{taskId}_/activate`*

- Activates a task
- Returns a `JaxbGenericResponse` with the status of the operation

[POST] *`/task/_{taskId}_/claim`*

- Claims a task
- Returns a `JaxbGenericResponse` with the status of the operation

[POST] *`/task/_{taskId}_/claimnextavailable`*

- Claims the next available task
- Returns a `JaxbGenericResponse` with the status of the operation
- Parameters: Takes an optional `language` query parameter.

[POST] *`/task/_{taskId}_/complete`*
- Completes a task
- Returns a `JaxbGenericResponse` with the status of the operation
- Parameters: Takes map query parameters, which are the "results" input for the complete operation

[POST] *`/task/_{taskId}_/delegate`*

- Delegates a task
- Returns a `JaxbGenericResponse` with the status of the operation
- Parameters: Requires a `targetId` query parameter, which identifies the user or group to which the task is delegated

[POST] *`/task/_{taskId}_/exit`*

- Exits a task
- Returns a `JaxbGenericResponse` with the status of the operation

[POST] *`/task/_{taskId}_/fail`*

- Fails a task
- Returns a `JaxbGenericResponse` with the status of the operation

[POST] *`/task/_{taskId}_/forward`*

- Delegates a task
- Returns a `JaxbGenericResponse` with the status of the operation
- Parameters: Requires a `targetId` query parameter, which identifies the user or group to which the task is forwarded

[POST] *`/task/_{taskId}_/nominate`*

- Nominates a task
- Returns a `JaxbGenericResponse` with the status of the operation
- Parameters: Requires at least one of either the `user` or `group` query parameter, which identify the user(s) or group(s) that are nominated for the task

[POST] *`/task/_{taskId}_/release`*

- Releases a task
- Returns a `JaxbGenericResponse` with the status of the operation

[POST] *`/task/_{taskId}_/resume`*

- Resumes a task
- Returns a `JaxbGenericResponse` with the status of the operation

[POST] *`/task/_{taskId}_/skip`*

- Skips a task
- Returns a `JaxbGenericResponse` with the status of the operation

[POST] *`/task/_{taskId}_/start`*

- Starts a task
- Returns a `JaxbGenericResponse` with the status of the operation

[POST] *`/task/_{taskId}_/stop`*
- Stops a task
- Returns a `JaxbGenericResponse` with the status of the operation

[POST] *`/task/_{taskId}_/suspend`*

- Suspends a task
- Returns a `JaxbGenericResponse` with the status of the operation

[GET] *`/task/_{taskId}_/showTaskForm`*

- Checks that the task idetified by _taskId_ exists and generates an URL to show the task form on a remote application.
- Returns a `JaxbTaskFormResponse` instance, that contains the URL to the task form.


==== Task query call

[GET] *`/task/query`*::
--
- The `/task/query` operation queries all non-archived tasks based on the parameters given.
- Returns a `JaxbTaskSummaryListResponse` with a list of `TaskSummaryImpl`
- Parameters: 
* Takes the following (case-'in' sensitive) query parameters listed below.
* All parameters except for the `union` parameter may be repeated.
`businessAdministrator`:: Returned tasks should have a business administrator identified by this parameter
`potentialOwner`:: Returned tasks should have a potential owner identified by this parameter
`processInstanceId`:: Returned tasks should be associated with the process instance identified by this parameter
`status`:: Returned tasks should have a status identified by this parameter
`taskId`:: Returned tasks should have the (task) id identified by this parameter
`taskOwner`:: Returned tasks should have a task owner (initiator) identified by this parameter
`workItemId`:: Returned tasks should be associated with the work item identified by this parameter
`language`:: Specifies the language that the returned tasks should be associated with
`union`:: This specifies whether the query should query the union or intersection of the parameters. +
  See below for an example and more info. +
  This parameter may only be passed _once_
--

{nbsp} +

.Query usage
================================================================================================
This call retrieves the task summaries of all tasks that have a work item id of 3, 4, _or_ 5. If you specify the _same_ parameter multiple times, the query
will select tasks that match _any_ of that parameter.
----
http://server:port/rest/task/query?workItemId=3&workItemId=4&workItemId=5
----
The next call will retrieve any task summaries for which the task id is 27 _and_ for
which the work item id is 11. Specifying _different_ parameters will result in a set of tasks that match _both_ (_all_) parameters.
----
`http://server:port/rest/task/query?workItemId=11&taskId=27`
----
The next call will retrieve any task summaries for which the task id is 27 _or_ the
work item id is 11. While these are different parameters, the `union` parameter is being used
here so that the union of the two queries (the work item id query and the task id query) is returned.
----
http://server:port/rest/task/query?workItemId=11&taskId=27&union=true`
----
The next call will retrieve any task summaries for which the status is `Created`
_and_ the potential owner of the task is `Bob`. Note that the letter case for the status
parameter value is case-'in'sensitve.
----
http://server:port/rest/task/query?status=creAted&potentialOwner=Bob`
----
The next call will return any task summaries for which the status is `Created`
_and_ the potential owner of the task is `bob`. Note that the potential owner parameter is
case-'sensitive'. `bob` is not the same user id as `Bob`!
----
http://server:port/rest/task/query?status=created&potentialOwner=bob`
----
The next call will return the _intersection_ of the set of task summaries for which the
process instance is 201, the potential owner is `bob` and for which the status is `Created`
_or_ `Ready`.
----
http://server:port/rest/task/query?status=created&status=ready&potentialOwner=bob&processInstanceId=201
----
That means that the task summaries that have the following characteristics would be included:

- process instance id 201, potential owner `bob`, status `Ready`
- process instance id 201, potential owner `bob`, status `Created`

And that following task summaries will _not_ be included:

- process instance id _183_, potential owner `bob`, status `Created`
- process instance id 201, potential owner '`mary`, status `Ready`
- process instance id 201, potential owner `bob`, status _`Complete`_
================================================================================================

==== Other Task calls

[GET] *`/task/_{taskId}_/content`*

- Gets the task content from a task identified by the given task id
- Returns: a `JaxbContent` with the content of the task
- Notes: 
* The _taskId_ component of the URL must conform to the following regex: `[0-9]+`

[GET] *`/task/content/_{contentId}_`*

- Gets the task content from a task identified by the given content id
- Returns a `JaxbContent` with the content of the task
- Notes: 
* The _contentId_ component of the URL must conform to the following regex: `[0-9]+`

[[remote.rest.deployment]]
=== Deployment Calls

The calls described in this section allow users to manage deployments. Deployments are in fact
`KieModule` JARs which can be deployed or undeployed, either via the UI or via the REST calls described
below. Configuration options, such as the runtime strategy, should be specified when deploying the deployment:
the configuration of a deployment can not be changed after it has already been deployed.

The above deploymentId regular expression describes an expression that contains the following elements, separated from eachother by a `:` character:

- The group id
- The artifact id
- The version
- The (optional) kbase id
- The (optional) ksession id

In a more formal sense, the _deploymentId_ component of the REST calls below must conform to the following regex:
----
`[\w\.-]+(:[\w\.-]+){2,2}(:[\w\.-]*){0,2}`
----

This regular expression is explained as follows:

- The `[\w\.-]` element, which occurs 3 times in the above regex, refers to a character set that can contain the following character sets:

.+[\w\.-]+ character sets
[cols="3*m^"]
|========================
| [A-Z] | [0-9] | .
| [a-z] | _     | -
|========================


This `[\w\.-]` element occurs at least 3 times and at most 5 times, separated by a `:` character each time.

.Accepted +deploymentId+'s
=============================
* `com.wonka:choco-maker:67.190`
* These example `deploymentId`'s contain the optional _kbase_ and _ksession_ id groups.
** `com.wonka:choco-maker:67.190:oompaBase`
** `com.wonka:choco-maker:67.190:oompaLoompaBase:gloopSession`
=============================

==== Asynchrous deployment calls

There are 2 operations that can be used to modify the status of a deployment:

* `/deployments/_{deploymentId}_/deploy`
* `/deployments/_{deploymentId}_/undeploy`

These `POST` deployment calls are both _asynchronous_, which
means that the information returned by the `POST` request does not reflect the
eventual final status of the operation itself.

[IMPORTANT]
====================================
As noted above, both the `/deploy` and `/undeploy` operations  are
_asynchronous_ REST operations. Successfull requests to these URLs will return the
status `202` upon the request completion. RFC 2616 defines the `202` status
as meaning the following: +

{nbsp} +

https://www.ietf.org/rfc/rfc2616.txt[RFC 2616]: +
"the request has been accepted for processing, but the processing has not been completed." +

{nbsp} +

This means the following:

. While the request may have been accepted "successfully", the operation itself (deploying or
undeploying the deployment unit) may actually fail.
. Furthermore, information about deployments, such as that retrieved by calling the `GET`
operations described below, are _snapshots_ and the information (including the status of the
deployment unit) may have changed by the time the user client receives the answer to the `GET` request.
====================================

=== Deployment call details


[GET] *`/deployment/`*

- Returns:: a list of all the available deployed instances in a `JaxbDeploymentUnitList` instance

[GET] *`/deployment/ _{deploymentId}_`*

- Returns a `JaxbDeploymentUnit` instance containing the information (including the configuration) of the deployment unit.
- Notes:
* This operation will fail when the URL uses a _deployementId_ that refers to a deployment unit
  that does not exist or for which the deployment has not yet been completed.
* This operation may succeed for deployment units for which an undeploy operation request has not
  yet completed.

[POST] *`/deployment/_{deploymentId}_/deploy`*

- Deploys the deployment unit referenced by the _deploymentId_
- Returns a `JaxbDeploymentJobResult` instance with the status of the _request_
- Parameters: Takes a `strategy` query parameter, which
* describes the runtime strategy used for the deployment.
* must have one of the following (case-_in_sensitive) values:
** `SINGLETON`
** `PER_REQUEST`
** `PER_PROCESS_INSTANCE`
* The default runtime strategy used for a deployment is `SINGLETON` .
- Notes:
* The deploy operation is an _asynchronous_ operation: the request can fail after
        being submitted. The status of the deployment can be retrieved using the `GET` calls
        described above. +
* It is possible to post a deployment descriptor (or a fragment of it) while
          submitting deploy request. That allows to override other deployment descriptors in
          the hierarchy. To do so the content type of the request must be set to `application/xml` and the request
  body should be a a valid deployment descriptor content. +
{nbsp} +
+
.Changing the audit logging mode from default JPA to JMS submit
=======
[source,xml,linenums,indent=0]
-------
<deployment-descriptor xsi:schemaLocation="http://www.jboss.org/jbpm deployment-descriptor.xsd" 
                       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <audit-mode>JMS</audit-mode>
</deployment-descriptor>
-------
=======
+
** Since deployment descriptors can be merged differently, it's possibile
  to provide the merge mode as part of deploy request by adding query
  parameter:
*** `mergemode` where values should be one of the following
**** KEEP_ALL
**** OVERRIDE_ALL
**** OVERRIDE_EMPTY
**** MERGE_COLLECTIONS

[POST] *`/deployment/_{deploymentId}_/undeploy`*

- Undeploys the deployment unit referenced by the `deploymentId`
- Returns a `JaxbDeploymentJobResult` instance with the status of the _request_
- Notes: 
* The undeploy operation is an _asynchronous_ operation. The status of the deployment can be 
  retrieved using the `GET` calls described above.

[[remote.rest.execute]]
=== Execute calls

While there is a `/runtime/{id}/execute` and a `task/execute` method, both will take all types
of commands. This is possible because execute takes a JaxbCommandsRequest object, which contains a list of
`(org.kie.api.command.)Command` objects. The `JaxbCommandsRequest` has fields to store the proper
`deploymentId` and `processInstanceId` information.

Of course, if you send a request with a command that needs this information (`deploymentId`, for example)
and don't fill the `deploymentId` in, the request will fail.


==== Execution call details

[POST] *`/execute`*

- Executes a `Command`
- Returns a `JaxbCommandResponse` implementation with the result of the operation

==== Commands accepted

.Runtime commands
[cols="3*d<"]
|===================================================================================================
| AbortWorkItemCommand                       | GetProcessInstancesCommand          | GetIdCommand  
| CompleteWorkItemCommand                    | SetProcessInstanceVariablesCommand  | SetGlobalCommand  
| GetWorkItemCommand                         | SignalEventCommand                  | 
|                                            | StartCorrelatedProcessCommand       | DeleteCommand  
| AbortProcessInstanceCommand                | StartProcessCommand                 | FireAllRulesCommand  
| GetProcessIdsCommand                       | GetVariableCommand                  | InsertObjectCommand  
| GetProcessInstanceByCorrelationKeyCommand  | GetFactCountCommand                 | UpdateCommand  
| GetProcessInstanceCommand                  | GetGlobalCommand  
|===================================================================================================


.Task commands
[cols="3*d<"]
|===================================================================================================
| ActivateTaskCommand            | FailTaskCommand                            | GetTasksOwnedCommand                         
| AddTaskCommand                 | ForwardTaskCommand                         | NominateTaskCommand                         
| CancelDeadlineCommand          | GetAttachmentCommand                       | ProcessSubTaskCommand                            
| ClaimNextAvailableTaskCommand  | GetContentCommand                          | ReleaseTaskCommand                         
| ClaimTaskCommand               | GetTaskAssignedAsBusinessAdminCommand      | ResumeTaskCommand                         
| CompleteTaskCommand            | GetTaskAssignedAsPotentialOwnerCommand     | SkipTaskCommand                         
| CompositeCommand               | GetTaskByWorkItemIdCommand                 | StartTaskCommand                         
| DelegateTaskCommand            | GetTaskCommand                             | StopTaskCommand                         
| ExecuteTaskRulesCommand        | GetTasksByProcessInstanceIdCommand         | SuspendTaskCommand                         
| ExitTaskCommand                | GetTasksByStatusByProcessInstanceIdCommand                         
|===================================================================================================


.History/Audit commands
[cols="3*d<"]
|===================================================================================================
| ClearHistoryLogsCommand           | FindProcessInstanceCommand     | FindSubProcessInstancesCommand            
| FindActiveProcessInstancesCommand | FindProcessInstancesCommand    | FindVariableInstancesByNameCommand            
| FindNodeInstancesCommand          | FindSubProcessInstancesCommand | FindVariableInstancesCommand            
|===================================================================================================

==== Basic example

The following `/rest/execute` call can be used to start a process (with process id '`evaluation`' in 
the project with deployment id '`org.jbpm:Evaluation:1.0`') and two parameters (parameter `employee` 
equal to '`krisv`' and `reason` equal to '`Yearly performance evaluation`').

[source,xml,linenums,indent=0]
----------------------------------------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<command-request>
  <deployment-id>org.jbpm:Evaluation:1.0</deployment-id>
  <ver>6.2.0.1</ver>
  <user>krisv</user>
  <start-process processId="evaluation">
    <parameter>
      <item key="reason">
        <value xsi:type="xs:string" xmlns:xs="http://www.w3.org/2001/XMLSchema"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">Yearly performance evaluation</value>
      </item>
      <item key="employee">
        <value xsi:type="xs:string" xmlns:xs="http://www.w3.org/2001/XMLSchema"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">krisv</value>
      </item>
    </parameter>
  </start-process>
</command-request>
----------------------------------------------------------------------------------------------------

Note that the request should also contain the following HTTP headers:

- A http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.17[Content-Type] header with the 
value of `application/xml` 
- A http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.8[Authorization] header with basic 
authentication information, as specificed by RFC2616 (see link).

The response will contain information about the process instance that was just started:

[source,xml,linenums,indent=0]
----------------------------------------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
  <command-response>
    <deployment-id>org.jbpm:Evaluation:1.0</deployment-id>
    <ver>6.2.0.1</ver>
    <process-instance index="0">
    <process-id>evaluation</process-id>
    <id>15</id>
    <state>1</state>
    <parentProcessInstanceId>0</parentProcessInstanceId>
    <command-name>StartProcessCommand</command-name>
  </process-instance>
</command-response>
----------------------------------------------------------------------------------------------------

==== More Complex Example with a Custom Data Type

The `/execute` operation also supports sending user-defined class instances as parameters in the 
command. This relies on JAXB for serialization and deserialization. To be able to deserialize the 
custom class on the server side, a "Kie-Deployment-Id" header must also be set to the deployment id 
of the project.

For example, when starting a process or completing a task, a user typically passes additional
parameters (process variable values or the result data for the completed task). These values are
then either primitives (Strings, ints, etc.) or user-defined classes that were created using the 
data modeler in the workbench, added directly to the deployed project or part of a dependency to 
the deployment (project).

The following request starts a process which contains a custom `TestObject` class (with two fields) 
as a parameter.

[source,xml,linenums,indent=0]
----------------------------------------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<command-request>
  <deployment-id>demo:testproject:1.0</deployment-id>
  <ver>6.2.0.1</ver>
  <user>krisv</user>
  <start-process processId="testproject.testprocess">
    <parameter>
      <item key="testobject">
        <value xsi:type="testObject" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
          <field1>1</field1>
          <field2>2</field2>
        </value>
      </item>
    </parameter>
  </start-process>
</command-request>
----------------------------------------------------------------------------------------------------

Just as in the basic example above, both a `Content-Type` and `Authorization` header should be set
in the request. 

The 3 headers that therefore need to be set in the requst are the following: 

- A http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.17[Content-Type] header with the 
value of `application/xml` 
- A http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.8[Authorization] header with basic 
authentication information, as specificed by RFC2616 (see link).
- A https://github.com/droolsjbpm/droolsjbpm-integration/blob/6.2.x/kie-remote/kie-remote-jaxb/src/main/java/org/kie/services/client/serialization/JaxbSerializationProvider.java#L73[Kie-Deployment-Id]
header with the value of the deployment id containing the class definitions of any parameters
sent with the command .

=== REST summary
	
The URL templates in the table below are relative to the one of the following URLs:

- `http://server:port/business-central/rest`
- `http://server:port/kie-wb/rest`

==== Runtime REST calls

[POST] *`/runtime/{deploymentId}/process/{procDefID}/start`*::
--
- start a process instance based on the Process definition (accepts query map parameters)
--
[POST] *`/runtime/{deploymentId}/process/{procDefID}/startform`*::
--
- returns a valid URL to the start process form to be shown on a client aplication.
--
[GET] *`/runtime/{deploymentId}/process/instance/{procInstanceID}`*::
--
- return a process instance details
--
[POST] *`/runtime/{deploymentId}/process/instance/{procInstanceID}/abort`*::
--
- abort the process instance
--
[POST] *`/runtime/{deploymentId}/process/instance/{procInstanceID}/signal`*::
--
- send a signal event to process instance (accepts query map parameters)
--
[GET] *`/runtime/{deploymentId}/process/instance/{procInstanceID}/variable/{varId}`*::
--
- return a variable from a process instance
--
[POST] *`/runtime/{deploymentId}/signal/{signalCode}`*::
--
- send a signal event to deployment
--
[POST] *`/runtime/{deploymentId}/workitem/{workItemID}/complete`*::
--
- complete a work item (accepts query map parameters)
--
[POST] *`/runtime/{deploymentId}/workitem/{workItemID}/abort`*::
--
- abort a work item
--
[POST] *`/runtime/{deploymentId}/withvars/process/{procDefinitionID}/start`*::
--
- start a process instance and return the process instance with its variables
--					
[GET] *`/runtime/{deploymentId}/withvars/process/instance/{procInstanceID}/`*::
--
- return a process instance with its variables
--					
[POST] *`/runtime/{deploymentId}/withvars/process/instance/{procInstanceID}/signal`*::
--
- send a signal event to the process instance (accepts query map parameters)
+
The following query parameters are accepted:
+ 
-- The `signal` parameter specifies the name of the signal to be sent
-- The `event` parameter specifies the (optional) value of the signal to be sent
--

==== Task REST calls
				

[GET] *`/task/query`*::
--
- return a TaskSummary list
--
[GET] *`/task/content/{contentID}`*::
--
- returns the content of a task
--
[GET] *`/task/{taskID}`*::
--
- return the task
--					
[POST] *`/task/{taskID}/activate`*::
--
- activate the task
--					
[POST] *`/task/{taskID}/claim`*::
--
- claim the task
--					
[POST] *`/task/{taskID}/claimnextavailable`*::
--
- claim the next available task
--				
[POST] *`/task/{taskID}/complete`*::
--
- complete the task (accepts query map paramaters)
--				
[POST] *`/task/{taskID}/delegate`*::
--
- delegate the task
--
[POST] *`/task/{taskID}/exit`*::
--
- exit the task
--					
[POST] *`/task/{taskID}/fail`*::
--
- fail the task
--					
[POST] *`/task/{taskID}/forward`*::
--
- forward the task
--					
[POST] *`/task/{taskID}/nominate`*::
--
- nominate the task
--					
[POST] *`/task/{taskID}/release`*::
--
- release the task
--					
[POST] *`/task/{taskID}/resume`*::
--
- resume the task (after suspending)
--					
[POST] *`/task/{taskID}/skip`*::
--
- skip the task
--					
[POST] *`/task/{taskID}/start`*::
--
- start the task
--					
[POST] *`/task/{taskID}/stop`*::
--
- stop the task
--					
[POST] *`/task/{taskID}/suspend`*::
--
- suspend the task
--					
[GET] *`/task/{taskID}/content`*::
--
- returns the content of a task
--					
[GET] *`/task/{taskID}/showTaskForm`*::
--
- returns a valid URL to the task form to be shown on a client aplication.
--


==== History REST calls
				
[POST] *`/history/clear/`*::
--
- delete all process, node and history records
--				
[GET] *`/history/instances`*::
--
- return the list of all process instance history records
--				
[GET] *`/history/instance/{procInstId}`*::
--
- return a list of process instance history records for a process instance
--				
[GET] *`/history/instance/{procInstId}/child`*::
--
- return a list of process instance history records for the subprocesses of the process instance
--				
[GET] *`/history/instance/{procInstId}/node`*::
--
- return a list of node history records for a process instance
--				
[GET] *`/history/instance/{procInstId}/node/{nodeId}`*::
--
- return a list of node history records for a node in a process instance
--				
[GET] *`/history/instance/{procInstId}/variable`*::
--
- return a list of variable history records for a process instance
--				
[GET] *`/history/instance/{procInstId}/variable/{variableId}`*::
--
- return a list of variable history records for a variable in a process instance
--				
[GET] *`/history/process/{procDefId}`*::
--
- return a list of process instance history records for process instances using a given process definition
--				
[GET] *`/history/variable/{varId}`*::
--
- return a list of variable history records for a variable
--				
[GET] *`/history/variable/{varId}/instances`*::
--
- return a list of process instance history records for process instances that contain a variable with the given variable id
--				
[GET] *`/history/variable/{varId}/value/{value}`*::
--
- return a list of variable history records for variable(s) with the given variable id and given value
--				
[GET] *`/history/variable/{varId}/value/{value}/instances`*::
--
- return a list of process instance history records for process instances with the specified variable that
contains the specified variable value
--				
	
====	Deployment REST calls

[GET] *`/deployments`*::
--
- return a list of (deployed) deployments
--				
[GET] *`/deployment/{deploymentId}`*::
--
- return the status and information about the deployment
--
[POST] *`/deployment/{deploymentId}/deploy`*::
--
- submit a request to deploy a deployment
--
[POST] *`/deployment/{deploymentId}/undeploy`*::
--
- submit a request to undeploy a deployment
--
