module.name=org.kie.kie-wb-webapp
module.type=dynamic
module.resources.unrequired=javax.xml.bind:jaxb-api:jar,com.sun.xml.bind:jaxb-impl:jar,com.sun.xml.bind:jaxb-xjc:jar,org.jboss.resteasy:jaxrs-api:jar,org.jboss.spec.javax.interceptor:jboss-interceptors-api_1.1_spec:jar,javax.transaction:jta:jar,log4j:log4j:jar,org.apache.ws.xmlschema:xmlschema-core:jar,javax.xml.stream:stax-api:jar,stax:stax-api:jar,org.jboss.spec.javax.servlet.jsp:jboss-jsp-api_2.2_spec:jar,javax.jms:jms:jar
module.patches.cdi-extensions=batik-extension-1.6-1,batik-script-1.6-1,camel-core-2.10.3,camel-josql-2.5.0,com.noelios.restlet-1.1.10,drools-compiler-6.0.0.CR2,fop-0.95,lucene-analyzers-common-4.0.0,,lucene-codecs-4.0.0,lucene-core-4.0.0,osgi-3.5.0.v20090520,prettytime-3.0.2.Final,seam-transaction-3.1.0.Final,sisu-inject-bean-2.2.3,smack-3.0.4,solder-impl-3.2.0.Final,xmlgraphics-commons-1.4,xpp3_min-1.1.4c
module.patches.webfragments=org.kie.kie-wb-webapp.xml
